package string3;

public class Program1 {

	static int lps(String s) {
        // code here
		int length=s.length();
		String answer="";
		for(int i=0;i<length;i++) {
			String prefix=s.substring(0, length-i-1);
			String suffix=s.substring(i+1);
			int prefixLength=prefix.length();
			int suffixLength=suffix.length();
			if((prefixLength==suffixLength) && prefix.equals(suffix)) {
				if(prefixLength>answer.length()) {
					answer=prefix;
					break;
				}
			}
		}
		return answer.length();
    }
	public static void main(String[] args) {
		System.out.println(lps("qxnjbnuxzlbpojukgycahvtpuskydgrweefftzesmhicqenyepblnubhmnfsuwoactfvulqisalkeykjplucgxjulomhmchoxomrzcatcldilnrabodhlobyfqfrsmiqaujbyluawzkjpckqqpxddaeksjcnymfyiocgcwiawsklwudolasqcwbxhfkfrpgbfihhgriejsrgouuzwopbmsyuxibqzhreryoypyebswjgsfhpwyqitqeqyghzpydhztfqrlrjhcrciargbjoubvmzbtaqsdztzgjssbebfxdpywvbhmxihjjkdjcxpcqoizgackciihxietjlhgwopfyupcreejunjcpnntvxbvhhqsuxaqlrwlmnnftupnjypyleujdxekeucatcrgupticgnvccklcbmqgizlffwlbalufecbtvjvbwsgbcrdefvmnuxsbtfewrybvacpvnmzjfhmhysngnztkxmlstqqkqritvzqilruqyiazapfopaaomliidzswsarqzhynbufzdhafxhvoivcwjmeolxkgzbwblwqmrvnwdodavzofuscdegssfeyhiwktsaflvujaknagmqngipmpygjdmjkufunxwulspuszjvhvlxewmsnkawqmfchmzwlvtwnitijcftasqeqeydpybhkijruiqgejettxdeaixabpgruexlcauojdidmylshqncnrgpzgrcvzwrfvejvyyecgkqgxkpnxrdoxuqdmubnsutnzclxapbibtozfdoduttuolxcgapyvioulztnqxwusmvyqjbkdwetievoekobtevgdrvwotqiglgwwjibgpuovpezasdvzydcryahsqqadwwaiebovyeqniqpcvmbtpgnqgukxkkajgctmghielytvqjxlvzhnhudnqnmdzpohrhtzqdddcxyuivgfwpsdlvtdkfgjwuqqdmpvpvytuwocuwhsncyyxrdkykvvgolmaahrvglrebtazdtmfrmekpoizmdiaoucrbtojggqhbqgelulegqqygzzuehutdwmhsaqagiiibqoonattsltaktvparkgowniyfifosprlffyhatzmnawgxnioxoevbmuhxbxrsocxvafwweijggrfwzuvqyrtnncmozdgpgflikjgrtpzbifxkbtabmtobwapxgxpmecwpldigujhfqhprcrtqmjrkmiishzglbecohkuewdjmkaemrzedkvowdyokxwwabyoklkojnzvyzbmqcrwnokjskacjwajzbzkojaxyauwzwlsyeonsaxmkzrvxrexufjiqjholcnlayfaetoytnlfmcajvgiqnradbkrmmezoceoizehuruzfybptjxlwrozuyrgkviaaookovrimnkulnjfxistzgvvemeqjmqlahwqepzqdlmqyvxvgqrhwoddchvlvmzxvxozmprraekabhyjxprwfwbhdwuaitxfqlgfcyyceifhqdrpuilzgogllalvwibowjtyjudncivulmkhwxgcmonzqaumivdgfwfoskexubrfpdolduprieqaeknoiqxpoefjojgimxpbddogzfxjjnjpzyghqfyfjeqxpwhcvyfybwecbdlnsuestkbjpaqagizxegzaghyjdfleiwtbtyvokwzcyscgacefkffrmfarkmyvkrydpttarteslgylkcsvizmwfoorcmmndmsvfmxzhbrshpfssypcxdycrmwwykjexdzcrybyzusikyaewrgvugymtwitgtzfyykqwlqxilgsjiyhaecukcifasbhnammbwezkwxshdmsnkbnqgkciskjnlsalgomfuoprljaqxtdjwtzcddlxnwkyqnmwbydwoupzdprckvlhqmjtqwqfudemqslrsophjggoyyriverlrdgjbwoyzukrmvjhmaovhujhucprhjeaoklpjbpkyacmxntjphgyesfauxsdgyfujqluubesdgecvyolhwjlopolmiouguormblgeqyjyfoufcfmaoapdqaryqlembyzdjhjbgvanjusnbgnricxyeowvadhbbigkqsmynolwkfjllycudzshqrequotvwchowvmjjzhtesgsqlotkidczhsvxosusckoxxxjygefylxownkivnlxufustnonraboxaxygcdepcvnrfvmsiloogijvyxmzacybcwhgbovfjiwoflioyyeghnbhmpgnufowdxchlzowhlmoyucwtgdcwgjiysvszloejslwratanfoncrjxzozvxkgvedpdpdiaxvwoxromxezbvlyxzzuwlctqgitxndxkbvyaponotopqznpzokxzmrpuzlrnqqzroyudohrjviaxxpwlbvkqmckoncdfuczictnrcgazocwlusyxojncnysccvhyyghczwtbdwbraxfwsduiohmbhfdjaliatrdtnywswzkxzrtrunbjxpmeuqqxdaxwrcrgbozxnlwmcqfyfgjcywhsmzprzpnsrfauvbsimovqgcpmlyqjuzbiytbzirrbwswttqbieyynbpzoqrxmraxrtyrdpifncdgytkgzigmlwnzofyayzxpuygyprfdtilrdxzcggrteevsltujuuzpshnjaumweanhxplfvcbbhwvsrpemjdddmqnnmblqdaxbpkiknjnuhiobyspjxspmkcbwfmmlmlm"));
	}
}
